services:
  storage1:
    build:
      context: .
      dockerfile: storage1/Dockerfile
    ports:
      - "9101:9101"

  storage2:
    build:
      context: .
      dockerfile: storage2/Dockerfile
    ports:
      - "9102:9102"

  load-balancer:
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
    depends_on:
      - storage1
      - storage2
    ports:
      - "9000:9000"
